services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"   # Metro Bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # Expo Go (Android)
      - "19002:19002" # Expo Go (iOS)
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - EXPO_PUBLIC_API_URL=http://backend:3000 # Use Docker internal networking
      - REACT_NATIVE_PACKAGER_HOSTNAME=10.150.148.252 # SET THIS TO YOUR LOCAL IP ADDRESS
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 # Expose Expo DevTools to docker internal

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development


# Build new containers when you make changes:
#   docker-compose up --build
# or
#   docker compose up --build
